### ISSUE TITLE
Setting remi_enabled_repositories has no effect

### ISSUE THREAD

**Issue by fkoyer** [robertdebock/ansible-role-remi#1]
## Describe the bug

I think the documentation might be out of date. If you attempt to set the php version using `remi_enabled_repositories` it still enables the default version.

## Playbook

```yaml
  roles:
    - role: robertdebock.remi
      remi_enabled_repositories:
        - php73
```

## Output

It enables the remi-php74 repository

## Suggested fix

Update the documentation to

```yaml
  roles:
    - role: robertdebock.remi
      remi_repository_selection: php73
```

## Environment

- Control node OS: Ubuntu 20.04.1 LTS
- Control node Ansible version: 2.9.6
- Managed node OS: CentOS 7
